intercambiar_producto/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("<slug:slug_intercambio>/", intercambiar_listar_mis_productos_view, name='intercambio listado'),
    path("<slug:slug_intercambio>/realizar_intercambio", realizar_intercambio_view, name='realizar intercambio'),
    path("ver_intercambios", ver_intercambios, name='ver_intercambios'),
    path('ver_detalle/<int:solicitud_id>/', detalle_intercambio, name='ver_detalle'),
    path('intercambios_por_sucursal_emp', intercambios_por_sucursal_view, name='intercambios_por_sucursal_emp'),
    path('confirmar_intercambio/<int:intercambio_id>/', confirmar_intercambio_view, name='confirmar_intercambio'),
    path('ausente_intercambio/<int:intercambio_id>/', ausente_intercambio_view, name='ausente_intercambio'),
    path('sin_venta/<int:intercambio_id>/', sin_venta_view, name='sin_venta'),
    path('registrar_venta/<int:intercambio_id>/', registrar_venta_view, name='registrar_venta'),
    path('marcar_venta/<int:intercambio_id>/', marcar_venta_view, name='marcar_venta'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("iniciar_sesion/", include("django.contrib.auth.urls")),
    path("iniciar_sesion/", include("iniciar_sesion.urls")),
    path("gestion_de_sucursales/", include("gestion_de_sucursales.urls")),
    path("gestion_de_usuarios/", include("gestion_de_usuarios.urls")),
    path("mis_productos/", include("mis_productos.urls")),
    path("busqueda_de_productos/", include("busqueda_de_productos.urls")),
    path("intercambiar_producto/", include("intercambiar_producto.urls")),
    path("gestion_de_servicios/", include("gestion_de_servicios.urls")),
    path("gestion_de_datos/", include("gestion_de_datos.urls")),
    path("catalogo/", include("catalogo.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intercambiar_producto/models.py
from django.db import models
from django.contrib.auth.models import User
from mis_productos.models import Producto
from catalogo.models import ProductoCatalogo
from gestion_de_sucursales.models import Sucursal
class Intercambio(models.Model):
    ESTADOS = (
        ('pendiente', 'Pendiente'),
        ('aceptado', 'Aceptado'),
        ('rechazado', 'Rechazado'),
        ('realizado', 'Realizado'),
        ('cancelado', 'Cancelado'),
        ('ausente', 'Ausente'),
    )


    producto_solicitante = models.ForeignKey(Producto, related_name='intercambios_solicitados', on_delete=models.CASCADE)
    producto_receptor = models.ForeignKey(Producto, related_name='intercambios_recibidos', on_delete=models.CASCADE)
    cliente_solicitante = models.ForeignKey(User, related_name='solicitudes_realizadas', on_delete=models.CASCADE)
    cliente_receptor = models.ForeignKey(User, related_name='solicitudes_recibidas', on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, choices=ESTADOS, default='pendiente')
    fecha_solicitud = models.DateTimeField(auto_now_add=True)
    dia = models.CharField(max_length=20, blank=True)
    fecha = models.DateField(null=True, blank=True)
    horario = models.IntegerField()
    venta_realizada = models.BooleanField(null=True, blank=True, default=None)
    def save(self, *args, **kwargs):
        if not self.dia:  
            self.dia = self.producto_receptor.dias  
        super().save(*args, **kwargs) 
    def __str__(self):
        return f"{self.producto_solicitante} <-> {self.producto_receptor} ({self.dia}) ({self.fecha}) ({self.horario}) ({self.estado})"

class Venta(models.Model):
    productos = models.ManyToManyField(ProductoCatalogo, through='ProductoVenta')
    fecha = models.DateTimeField(auto_now_add=True)
    monto_total = models.DecimalField(max_digits=10, decimal_places=2)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE,null=True, blank=True)
    def __str__(self):
        return f"Venta {self.id} - {self.fecha} - ${self.monto_total}"

class ProductoVenta(models.Model):
    producto = models.ForeignKey(ProductoCatalogo, on_delete=models.CASCADE)
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.producto.nombre} - {self.cantidad} unidades"

intercambiar_producto/forms.py
from django import forms
from .models import Intercambio
import datetime

class IntercambioForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.producto_receptor = kwargs.pop('producto_receptor', None)
        horario_choices = kwargs.pop('horario_choices', [])
        super().__init__(*args, **kwargs)
        self.fields['horario'] = forms.ChoiceField(choices=horario_choices)
        if self.producto_receptor and self.producto_receptor.dias: 
            self.fields['dia'].widget = forms.Select(choices=[(dia, dia) for dia in self.producto_receptor.dias])
        if horario_choices:
            self.fields['horario'] = forms.ChoiceField(choices=horario_choices)
        

    class Meta:
        model = Intercambio
        exclude = ['producto_solicitante', 'producto_receptor', 'cliente_solicitante', 'cliente_receptor', 'estado']
        fields = ['dia', 'fecha', 'horario','producto_receptor']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),
        }
    
    def clean(self):
        cleaned_data = super().clean()
        dia = cleaned_data.get('dia')
        fecha = cleaned_data.get('fecha')
        producto_receptor = cleaned_data.get("producto_receptor")
        
        if self.producto_receptor:
            dia = self.producto_receptor.dias
        else:
            dia = producto_receptor.dias
        if fecha:
            hoy = datetime.date.today()
            if fecha <= hoy:
                raise forms.ValidationError("La fecha seleccionada debe ser posterior al día de hoy.")

        dias_mapping = {
            'Lunes': 'Monday',
            'Martes': 'Tuesday',
            'Miércoles': 'Wednesday',
            'Jueves': 'Thursday',
            'Viernes': 'Friday',
            'Sábado': 'Saturday',
            'Domingo': 'Sunday'
        }

        if not self.producto_receptor:
            raise forms.ValidationError("Producto receptor no definido.")
        
        dia = self.producto_receptor.dias
        fecha = cleaned_data.get('fecha')
        
        if fecha:
            dia_semana = fecha.strftime('%A') 
            dia_semana = dia_semana.capitalize() 

            if dia not in dias_mapping:
                raise forms.ValidationError(f"Día '{dia}' no está en el mapeo de días.")

            if dias_mapping[dia] != dia_semana:
                raise forms.ValidationError("La fecha seleccionada no coincide con el día de semana disponible.")
        return cleaned_data

intercambiar_producto/views.py
from django.shortcuts import render
from mis_productos.models import Producto
from iniciar_sesion import *
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Intercambio,Venta, ProductoVenta
from catalogo.models import ProductoCatalogo
from .forms import IntercambioForm
from django.db.models import Q
from datetime import datetime, timedelta
from gestion_de_sucursales.models import PerfilEmpleado
from django.utils import timezone
from gestion_de_sucursales.models import Sucursal


@soy_cliente
def intercambiar_listar_mis_productos_view(request, slug_intercambio):
    usuario = request.user
    producto_receptor = Producto.objects.get(slug=slug_intercambio)
    
    intercambios_existentes = Intercambio.objects.filter(
        Q(estado__in=['aceptado', 'realizado']) & (
            Q(producto_solicitante__cliente=usuario) |
            Q(producto_receptor__cliente=usuario)
        ) 
    )
    productos_excluir = set()
    for intercambio in intercambios_existentes:
        if intercambio.producto_solicitante.cliente == usuario:
            productos_excluir.add(intercambio.producto_solicitante.id)
        if intercambio.producto_receptor.cliente == usuario:
            productos_excluir.add(intercambio.producto_receptor.id)
    productos_excluir_list = list(productos_excluir)
    queryset = Producto.objects.filter(cliente=usuario, categoria=producto_receptor.categoria).exclude(id__in=productos_excluir_list)

    context = {
        "lista": queryset,
        "slug_intercambio": slug_intercambio,
    }
    
    return render(request, "intercambiar_producto/intercambiar_listado.html", context)

@soy_cliente
def realizar_intercambio_view(request, slug_intercambio):
    producto_receptor = Producto.objects.get(slug=slug_intercambio)
    hora_inicio_str = producto_receptor.horario_inicio.split(':')[0]
    hora_fin_str = producto_receptor.horario_fin.split(':')[0]
    hora_inicio = int(hora_inicio_str)
    hora_fin = int(hora_fin_str)
    horarios_disponibles = [(hora, str(hora)) for hora in range(hora_inicio, hora_fin + 1)]

    if request.method == 'POST':
        producto_solicitante_id = request.POST.get('producto_solicitante_id')
        producto_solicitante = Producto.objects.get(id=producto_solicitante_id)
        fecha = request.POST.get('fecha')
        if fecha:
            form = IntercambioForm(request.POST, horario_choices=horarios_disponibles, producto_receptor=producto_receptor)
            if form.is_valid():
                producto_solicitante_id = request.POST.get('producto_solicitante_id')
                try:
                    producto_solicitante = Producto.objects.get(id=producto_solicitante_id)
                except Producto.DoesNotExist:
                    messages.error(request, "Producto solicitante no encontrado.")
                    return redirect("intercambiar_producto/intercambiar_listado.html")
                
                intercambio = form.save(commit=False)
                intercambio.producto_solicitante = producto_solicitante
                intercambio.cliente_solicitante = request.user
                intercambio.producto_receptor = producto_receptor
                intercambio.cliente_receptor = producto_receptor.cliente
                intercambio.dia = producto_receptor.dias
                intercambio.estado = 'pendiente'
                intercambio.save()
                messages.success(request, "Solicitud de intercambio enviada con éxito.")
                return redirect('homepage')
            else:
                for field, errors in form.errors.items():
                    for error in errors:
                        messages.error(request, error)
        else:
            messages.error(request, "La fecha es obligatoria.")
            form = IntercambioForm(request.POST, horario_choices=horarios_disponibles, producto_receptor=producto_receptor)
            return render(request, "intercambiar_producto/realizar_intercambio.html", {'producto_receptor': producto_receptor,
        'horarios_disponibles': horarios_disponibles,'form': form})
    else:
        producto_solicitante_id = request.GET.get('producto_solicitante_id')
        try:
            producto_solicitante = Producto.objects.get(id=producto_solicitante_id)
        except Producto.DoesNotExist:
            messages.error(request, "Producto solicitante no encontrado.")
            return redirect("intercambiar_producto/intercambiar_listado.html")
        
        form = IntercambioForm(horario_choices=horarios_disponibles, producto_receptor=producto_receptor)

    return render(request, 'intercambiar_producto/realizar_intercambio.html', {
        'form': form,
        'producto_solicitante': producto_solicitante,
        'producto_receptor': producto_receptor,
        'horarios_disponibles': horarios_disponibles
    })

@soy_cliente
def ver_intercambios(request):
    usuario_actual = request.user
    solicitudes_enviadas = Intercambio.objects.filter(cliente_solicitante=usuario_actual,estado="pendiente")
    solicitudes_recibidas = Intercambio.objects.filter(cliente_receptor=usuario_actual,estado="pendiente" )

    # Solicitudes aceptadas
    solicitudes_aceptadas = Intercambio.objects.filter(
        Q(cliente_receptor=usuario_actual) | Q(cliente_solicitante=usuario_actual),
        estado="aceptado"
    )

    # Solicitudes realizadas
    solicitudes_realizadas = Intercambio.objects.filter(
        Q(cliente_receptor=usuario_actual) | Q(cliente_solicitante=usuario_actual),
        estado="realizado"
    )

    # Solicitudes canceladas
    solicitudes_canceladas = Intercambio.objects.filter(
        Q(cliente_receptor=usuario_actual) | Q(cliente_solicitante=usuario_actual),
        estado="cancelado"
    )

    # Solicitudes ausentes
    solicitudes_ausentes = Intercambio.objects.filter(
        Q(cliente_receptor=usuario_actual) | Q(cliente_solicitante=usuario_actual),
        estado="ausente"
    )

    # Solicitudes rechazadas
    solicitudes_rechazadas = Intercambio.objects.filter(
        Q(cliente_receptor=usuario_actual) | Q(cliente_solicitante=usuario_actual),
        estado="rechazada"
    )
    no_hay_intercambios = (
        not solicitudes_enviadas.exists() and
        not solicitudes_recibidas.exists() and
        not solicitudes_aceptadas.exists() and
        not solicitudes_realizadas.exists() and
        not solicitudes_canceladas.exists() and
        not solicitudes_rechazadas.exists() and
        not solicitudes_ausentes.exists()
    )

    if request.method == 'POST':
        intercambio_id = request.POST.get('intercambio_id')
        if intercambio_id:
            try:
                intercambio = Intercambio.objects.get(id=intercambio_id)
                intercambio.delete()
                messages.success(request, "Solicitud cancelada con éxito")
            except Intercambio.DoesNotExist:
                messages.error(request, "La solicitud no existe")
        else:
            messages.error(request, "Algo salió mal")

    context = {
        'solicitudes_enviadas': solicitudes_enviadas,
        'solicitudes_recibidas': solicitudes_recibidas,
        'solicitudes_aceptadas': solicitudes_aceptadas,
        'solicitudes_realizadas': solicitudes_realizadas,
        'solicitudes_canceladas': solicitudes_canceladas,
        'solicitudes_ausentes': solicitudes_ausentes, 
        'solicitudes_rechazadas': solicitudes_rechazadas, 
        'no_hay_intercambios': no_hay_intercambios,
    }
    return render(request, "intercambiar_producto/ver_intercambios.html", context)

@soy_cliente
def detalle_intercambio(request, solicitud_id):
    solicitud = Intercambio.objects.get(id=solicitud_id)
    
    if request.method == "POST":
        accion = request.POST.get('accion')
        if accion == 'aceptar':
            producto_s = solicitud.producto_solicitante
            producto_r = solicitud.producto_receptor 

            # Rechazar todas las solicitudes pendientes que involucren los mismos productos en cualquier dirección
            solicitudes_a_rechazar = Intercambio.objects.filter(producto_receptor=producto_r).exclude(id=solicitud_id)
            solicitudes_a_rechazar_dos = Intercambio.objects.filter(producto_solicitante=producto_s).exclude(id=solicitud_id)
            
            # Actualiza el estado a 'rechazado' y guarda cada solicitud
            for s in solicitudes_a_rechazar:
                s.estado = 'rechazado'
                s.save()

            # Actualiza el estado a 'rechazado' y guarda cada solicitud
            for s_dos in solicitudes_a_rechazar_dos:
                s_dos.estado = 'rechazado'
                s_dos.save()

            solicitud.estado = 'aceptado'
            solicitud.save()
            messages.success(request, "La solicitud ha sido aceptada.")
        elif accion == 'rechazar':
            solicitud.estado = 'rechazado'
            solicitud.save()
            messages.success(request, "La solicitud ha sido rechazada.")
        elif accion == 'cancelar':
            ahora = timezone.now()  # Hora actual con zona horaria

            # Crear un datetime para el horario del intercambio con la fecha pactada y hora
            horario_intercambio = datetime.combine(solicitud.fecha, datetime.min.time()) + timedelta(hours=solicitud.horario)
            
            # Asegurarse de que horario_intercambio sea consciente de la zona horaria
            horario_intercambio = timezone.make_aware(horario_intercambio, timezone.get_current_timezone())

            diferencia = horario_intercambio - ahora
            
            if diferencia > timedelta(hours=1):
                solicitud.delete()
                messages.success(request, "Solicitud cancelada con éxito")
            else:
                messages.error(request, "No podes cancelar el intercambio con menos de una hora de anticipación. De ausentarse, volveran a ofertarse ambos productos.")

intercambiar_producto/templates/intercambiar_producto/intercambiar_listado.html
{% extends "homepage/base.html" %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% block content %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% if lista %}
                {% for producto in lista %}
                    <div class="col">
                        <div class="card">
                            <img src="{{ producto.imagen_principal.url }}" class="card-img-top img-thumbnail" alt="{{ producto.nombre }}" style="height: 300px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ producto.nombre }}</h5>
                                <a href="{% url 'realizar intercambio' slug_intercambio %}?producto_solicitante_id={{ producto.id }}" class="btn btn-primary stretched-link">Intercambiar</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h1 class="display-1">No tenes productos de esta categoria para intercambiar</h1>
            {% endif %}
        </div>
    {% endblock %}
    </body>
</html>

intercambiar_producto/templates/intercambiar_producto/intercambios_por_sucursal.html
{% extends "homepage/base.html" %}

{% block content %}
<h2>Intercambios en la sucursal {{ sucursal.nombre }}</h2>

<form method="get" action="{% url 'intercambios_por_sucursal_emp' %}">
    <label for="id_fecha">Seleccionar Fecha:</label>
    <input type="date" id="id_fecha" name="fecha" value="{{ fecha_seleccionada }}">
    <button type="submit">Filtrar</button>
</form>

{% if intercambios %}
<table class="table">
    <thead>
        <tr>
            <th>Producto Solicitante</th>
            <th>Producto Receptor</th>
            <th>Cliente Solicitante</th>
            <th>Cliente Receptor</th>
            <th>Estado</th>
            <th>Fecha de Solicitud</th>
            <th>Día</th>
            <th>Fecha</th>
            <th>Horario</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for intercambio in intercambios %}
        <tr>
            <td>{{ intercambio.producto_solicitante.nombre }}</td>
            <td>{{ intercambio.producto_receptor.nombre }}</td>
            <td>{{ intercambio.cliente_solicitante.username }}</td>
            <td>{{ intercambio.cliente_receptor.username }}</td>
            <td>{{ intercambio.estado }}</td>
            <td>{{ intercambio.fecha_solicitud }}</td>
            <td>{{ intercambio.dia }}</td>
            <td>{{ intercambio.fecha }}</td>
            <td>{{ intercambio.horario }}</td>
            <td>
                {% if intercambio.estado == 'aceptado' %}
                <form method="post" action="{% url 'confirmar_intercambio' intercambio.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Confirmar</button>
                </form>
                <form method="post" action="{% url 'ausente_intercambio' intercambio.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Ausente</button>
                </form>
                {% elif intercambio.estado == 'realizado' %}
                {% if intercambio.venta_realizada is None and catalogo %}
                <form method="post" action="{% url 'marcar_venta' intercambio.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Marcar Venta</button>
                </form>
                <form method="post" action="{% url 'sin_venta' intercambio.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Sin Venta</button>
                </form>
                {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No hay intercambios programados para hoy en esta sucursal.</p>
{% endif %}

{% endblock %}

intercambiar_producto/templates/intercambiar_producto/realizar_intercambio.html
<!-- templates/crear_intercambio.html -->
{% extends "homepage/base.html" %}
{% block content %}
<div class="container">
    <h1>Crear Intercambio</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="producto_solicitante_id" value="{{ producto_solicitante.id }}">
        <div class="mb-3">
            <label for="producto_solicitante" class="form-label"><strong>Producto Solicitante:</strong> {{ producto_solicitante.nombre }}</label>
        </div>
        <div class="mb-3">
            <label for="producto_receptor" class="form-label"><strong>Producto Receptor:</strong>{{ producto_receptor.nombre }}</label>
            <p></p>
        </div>
        <div class="mb-3">
            <label for="cliente_solicitante" class="form-label"><strong>Cliente Solicitante:</strong> {{ request.user }}</label>
        </div>
        <div class="mb-3">
            <label for="cliente_receptor" class="form-label"><strong>Cliente Receptor:</strong> {{ producto_receptor.cliente }}</label>
        </div>
        <div class="mb-3">
            <label for="producto_receptor.sucursal" class="form-label"><strong>Sucursal y Ciudad:</strong> {{producto_receptor.sucursal }} - {{producto_receptor.sucursal.ciudad }}</label>
        </div>
        <div class="mb-3">
            <label for="producto_receptor" class="form-label"><strong>Dia:</strong> {{ producto_receptor.dias }}</label>
        </div>
        <div class="form-group">
            <label for="id_fecha" ><strong>Fecha:</strong></label>
            {{ form.fecha }}
        </div>
        <div class="mb-3">
            <label for="horario" class="form-label" ><strong>Horario:</strong></label>
            <select class="form-select" id="horario" name="horario" required>
                <option value="" selected disabled>Selecciona un horario</option>
                {% for valor, etiqueta in form.horario.field.choices %}
                    <option value="{{ valor }}">{{ etiqueta }}</option>
                {% endfor %}
            </select>
        </div>
                
        <button type="submit" class="btn btn-primary">Solicitar Intercambio</button>
    </form>
</div>




{% endblock %}

intercambiar_producto/templates/intercambiar_producto/registrar_venta.html
{% extends "homepage/base.html" %}
{% block content %}
<div class="container mt-5">
    <h1>Registrar Venta</h1>
    <form method="post" id="ventaForm">
        {% csrf_token %}
        <div class="form-group">
            <label for="monto_total">Monto Total</label>
            <input type="number" class="form-control" id="monto_total" name="monto_total" step="0.01" min="1" required>
        </div>
        <div class="form-group">
            <label>Productos</label>
            {% for producto in productos %}
            <div class="form-check">
                <input class="form-check-input producto-checkbox" type="checkbox" value="{{ producto.id }}"
                    id="producto{{ producto.id }}" name="producto">
                <label class="form-check-label" for="producto{{ producto.id }}">
                    {{ producto.nombre }}
                </label>
                <input type="number" class="form-control mt-2 cantidad-input" name="cantidad-{{ producto.id }}"
                    placeholder="Cantidad" min="1" style="display: none;">
            </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Registrar Venta</button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const checkboxes = document.querySelectorAll('.producto-checkbox');

        checkboxes.forEach(checkbox => {
            checkbox.addEventListener('change', function () {
                const cantidadInput = this.closest('.form-check').querySelector('.cantidad-input');
                if (this.checked) {
                    cantidadInput.style.display = 'block';
                    cantidadInput.required = true;
                } else {
                    cantidadInput.style.display = 'none';
                    cantidadInput.required = false;
                    cantidadInput.value = '';  // Limpiar el valor del input
                }
            });
        });

        const form = document.getElementById('ventaForm');
        form.addEventListener('submit', function (event) {
            const checkboxes = document.querySelectorAll('.producto-checkbox');
            let validForm = false;

            checkboxes.forEach(checkbox => {
                const cantidadInput = checkbox.closest('.form-check').querySelector('.cantidad-input');
                if (checkbox.checked && cantidadInput.value.trim() === '') {
                    validForm = false;
                    cantidadInput.reportValidity();
                } else {
                    validForm = true;
                }
            });

            if (!validForm) {
                event.preventDefault();
            }
        });
    });
</script>
{% endblock %}