catalogo/urls.py
from django.urls import path
from catalogo import views

urlpatterns = [
    path("subir_producto_catalogo/", views.subir_producto, name='subir_producto_catalogo'),
    path("listar_catalogo/", views.ver_catalogo, name='listar_catalogo'),
    path("historial_productos/", views.ver_historial, name='ver_historial'),
    path("eliminar_producto/<slug:slug>/", views.eliminar_producto, name='eliminar_producto'),
    path("restaurar_producto/<slug:slug>/", views.restaurar_producto, name='restaurar_producto'),
    path('editar_producto/<slug:slug>/', views.editar_producto, name='editar_producto'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("iniciar_sesion/", include("django.contrib.auth.urls")),
    path("iniciar_sesion/", include("iniciar_sesion.urls")),
    path("gestion_de_sucursales/", include("gestion_de_sucursales.urls")),
    path("gestion_de_usuarios/", include("gestion_de_usuarios.urls")),
    path("mis_productos/", include("mis_productos.urls")),
    path("busqueda_de_productos/", include("busqueda_de_productos.urls")),
    path("intercambiar_producto/", include("intercambiar_producto.urls")),
    path("gestion_de_servicios/", include("gestion_de_servicios.urls")),
    path("gestion_de_datos/", include("gestion_de_datos.urls")),
    path("catalogo/", include("catalogo.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
from django.db import models
from django.db import models
from django.utils.text import slugify

class ProductoCatalogo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=500)
    imagen_principal = models.ImageField(upload_to='imagenes/')
    imagen_extra1 = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    imagen_extra2 = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    imagen_extra3 = models.ImageField(upload_to='imagenes/', blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    visible = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nombre)
        super(ProductoCatalogo, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

catalogo/forms.py
# forms.py

from django import forms
from .models import ProductoCatalogo

class ProductoForm(forms.ModelForm):
    class Meta:
        model = ProductoCatalogo
        fields = ['descripcion', 'imagen_principal', 'imagen_extra1', 'imagen_extra2', 'imagen_extra3']

catalogo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from catalogo.models import ProductoCatalogo
from catalogo.forms import ProductoForm
from iniciar_sesion import *
@super_user 
def subir_producto(request):
    if request.method == 'POST':
        # Obtener los datos del formulario enviado por el usuario
        nombre = request.POST.get('nombre')
        descripcion = request.POST.get('descripcion')
        imagen_principal = request.FILES.get('imagen_principal')
        imagen_extra1 = request.FILES.get('imagen_extra1')
        imagen_extra2 = request.FILES.get('imagen_extra2')
        imagen_extra3 = request.FILES.get('imagen_extra3')

        # Verificar si el nombre del producto ya existe
        if ProductoCatalogo.objects.filter(nombre=nombre).exists():
            messages.error(request, "El nombre del producto ya está registrado.")
            return render(request, 'catalogo/subir_producto_catalogo.html')

        # Crear una instancia de ProductoCatalogo con los datos del formulario
        producto_catalogo = ProductoCatalogo(
            nombre=nombre,
            descripcion=descripcion,
            # Guardar las imágenes en los campos correspondientes
            imagen_principal=imagen_principal,
            imagen_extra1=imagen_extra1,
            imagen_extra2=imagen_extra2,
            imagen_extra3=imagen_extra3
        )
        producto_catalogo.save()

        messages.success(request, "Producto registrado en el catálogo exitosamente.")
        return redirect('subir_producto_catalogo')  # Redirigir a la misma página para un nuevo formulario

    return render(request, "catalogo/subir_producto_catalogo.html")

def ver_catalogo(request):
    catalogo = ProductoCatalogo.objects.filter(visible=True)
    
    context = {
        'catalogo': catalogo,
    }
    return render(request, "catalogo/listar_catalogo.html", context)
@super_user 
def ver_historial(request):
    catalogo = ProductoCatalogo.objects.filter(visible=False)
    
    context = {
        'catalogo': catalogo,
    }
    return render(request, "catalogo/historial_productos.html", context)

@super_user 
def eliminar_producto(request, slug):
    producto = ProductoCatalogo.objects.get(slug=slug)
    producto.visible = False
    producto.save()
    return redirect('listar_catalogo')
    
@super_user 
def restaurar_producto(request, slug):
    producto = ProductoCatalogo.objects.get(slug=slug)
    producto.visible = True
    producto.save()
    return redirect('ver_historial')

@super_user 
def editar_producto(request, slug):
    producto = ProductoCatalogo.objects.get(slug=slug)
    
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('listar_catalogo')  # Redirigir a la página del catálogo después de guardar los cambios
    else:
        form = ProductoForm(instance=producto)
    
    return render(request, 'catalogo/editar_producto.html', {'form': form, 'producto': producto})

catalogo/templates/catalogo/editar_producto.html
<!-- editar_producto.html -->

{% extends "homepage/base.html" %}
{% block content %}
<h2 class="text-center">Editar Producto</h2>
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
  <div class="card bg-light shadow p-4" style="background-color: rgba(255, 255, 255, 0.8);">
    <h2 class="text-center">{{ producto.nombre }}</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary w-100">Guardar Cambios</button>
    </form>
  </div>
</div>
{% endblock %}

catalogo/templates/catalogo/historial_productos.html
{% extends "homepage/base.html" %}

{% block content %}
<div class="container">
  <h2 class="text-center">Historial de productos</h2>

  <div class="row">
    {% for producto in catalogo %}
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div id="carouselExample{{ forloop.counter }}" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ producto.imagen_principal.url }}" class="d-block w-100" alt="...">
            </div>
            {% if producto.imagen_extra1 %}
            <div class="carousel-item">
              <img src="{{ producto.imagen_extra1.url }}" class="d-block w-100" alt="...">
            </div>
            {% endif %}
            {% if producto.imagen_extra2 %}
            <div class="carousel-item">
              <img src="{{ producto.imagen_extra2.url }}" class="d-block w-100" alt="...">
            </div>
            {% endif %}
            {% if producto.imagen_extra3 %}
            <div class="carousel-item">
              <img src="{{ producto.imagen_extra3.url }}" class="d-block w-100" alt="...">
            </div>
            {% endif %}
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample{{ forloop.counter }}" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample{{ forloop.counter }}" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ producto.nombre }}</h5>
          <p class="card-text">{{ producto.descripcion }}</p>
          {% if request.user.is_superuser %}
          <a href="{% url 'restaurar_producto' slug=producto.slug %}" class="btn btn-danger btn-sm mt-2" onclick="return confirm('¿Estás seguro de que deseas restaurar este producto?');">Restaurar</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col-12">
      <div class="alert alert-warning" role="alert">
        No hay productos en el historial.
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

catalogo/templates/catalogo/listar_catalogo.html
{% extends "homepage/base.html" %}

{% block content %}
<div class="container">
  <h2 class="text-center">Catálogo</h2>

  <div class="row">
    {% for producto in catalogo %}
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <div id="carouselExample{{ forloop.counter }}" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ producto.imagen_principal.url }}" class="d-block w-100" alt="...">
            </div>
            {% if producto.imagen_extra1 %}
            <div class="carousel-item">
              <img src="{{ producto.imagen_extra1.url }}" class="d-block w-100" alt="...">
            </div>
            {% endif %}
            {% if producto.imagen_extra2 %}
            <div class="carousel-item">
              <img src="{{ producto.imagen_extra2.url }}" class="d-block w-100" alt="...">
            </div>
            {% endif %}
            {% if producto.imagen_extra3 %}
            <div class="carousel-item">
              <img src="{{ producto.imagen_extra3.url }}" class="d-block w-100" alt="...">
            </div>
            {% endif %}
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample{{ forloop.counter }}" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample{{ forloop.counter }}" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ producto.nombre }}</h5>
          <p class="card-text">{{ producto.descripcion }}</p>
          {% if request.user.is_superuser %}
          <a href="{% url 'editar_producto' slug=producto.slug %}" class="btn btn-warning btn-sm">Modificar</a>
          <a href="{% url 'eliminar_producto' slug=producto.slug %}" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar este producto?');">Eliminar</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col-12">
      <div class="alert alert-warning" role="alert">
        No hay productos en el catálogo.
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

catalogo/templates/catalogo/subir_producto_catalogo.html
<!-- subir_producto.html -->

{% extends "homepage/base.html" %}
{% load static %}

{% block content %}
<h3 class="mt-4 text-center">Subir Producto al Catálogo</h3>
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card bg-dark text-white p-4" style="width: 30rem;">
        <form id="register-form" action="{% url 'subir_producto_catalogo' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card-body">
                <h5 class="card-title">Complete todos los campos</h5>
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre" required>
                </div>
                <div class="form-group">
                    <label for="descripcion">Descripción</label>
                    <input type="text" class="form-control" id="descripcion" name="descripcion" placeholder="Descripción" required>
                </div>
                <div class="custom-file mb-3">
                    <input type="file" id="id_imagen_principal" name="imagen_principal" class="custom-file-input" accept=".jpg, .jpeg, .png">
                    <label class="custom-file-label" for="id_imagen_principal"><strong>Selecciona la imagen principal (OBLIGATORIA)</strong></label>
                </div>
                <div class="custom-file mb-3">
                    <input type="file" id="id_imagen_extra1" name="imagen_extra1" class="custom-file-input" disabled accept=".jpg, .jpeg, .png">
                    <label class="custom-file-label" for="id_imagen_extra1">Selecciona otra imagen <strong>(opcional)</strong></label>
                </div>
                <div class="custom-file mb-3">
                    <input type="file" id="id_imagen_extra2" name="imagen_extra2" class="custom-file-input" disabled accept=".jpg, .jpeg, .png">
                    <label class="custom-file-label" for="id_imagen_extra2">Selecciona otra imagen <strong>(opcional)</strong></label>
                </div>
                <div class="custom-file mb-3">
                    <input type="file" id="id_imagen_extra3" name="imagen_extra3" class="custom-file-input" disabled accept=".jpg, .jpeg, .png">
                    <label class="custom-file-label" for="id_imagen_extra3">Selecciona otra imagen <strong>(opcional)</strong></label>
                </div>
                <button class="btn btn-primary btn-block mt-4" type="submit">Subir producto</button>
            </div>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_imagen_principal').change(function() {
            $('#id_imagen_extra1').prop('disabled', false);
        });
        $('#id_imagen_extra1').change(function() {
            $('#id_imagen_extra2').prop('disabled', false);
        });
        $('#id_imagen_extra2').change(function() {
            $('#id_imagen_extra3').prop('disabled', false);
        });
    });
</script>
{% endblock %}