gestion_de_servicios/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", mis_servicios_view, name='mis_servicios'),
    path("listar_solicitudes/", listar_solicitudes_view, name='listar_solicitudes'),
    path("solicitar_servicio/", subir_servicio_view, name='subir_servicio'),
    path("listar_solicitudes/<slug:slug>/", ver_imagen_view, name='ver_imagen'),
    path("listar_solicitudes/pagar/<slug:slug>/", pagar_publicacion_view, name='pagar_publicacion'),
    path("listar_solicitudes_clientes/", listar_solicitudes_clientes_view, name='listar_solicitudes_clientes'),
    path("listar_solicitudes_clientes/<slug:slug>/", evaluar_servicio_view, name='evaluar_servicio'),
    path("listar_solicitudes_clientes/<slug:slug>/motivo", mandar_motivo_view, name='mandar_motivo'),
    path('servicios_publicados', servicios_publicados_view, name='servicios_publicados'),
    path("historial_servicios/", ver_historial_view, name='ver_historial_servicios'),
    path("eliminar_servicio/<slug:slug>/", eliminar_servicio_view, name='eliminar_servicio'),
    path('configuracion-servicio/', configuracion_servicio, name='configuracion_servicio'),
    path('eliminar_servicio/<slug:slug>/', eliminar_servicio, name='eliminar_servicio'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("iniciar_sesion/", include("django.contrib.auth.urls")),
    path("iniciar_sesion/", include("iniciar_sesion.urls")),
    path("gestion_de_sucursales/", include("gestion_de_sucursales.urls")),
    path("gestion_de_usuarios/", include("gestion_de_usuarios.urls")),
    path("mis_productos/", include("mis_productos.urls")),
    path("busqueda_de_productos/", include("busqueda_de_productos.urls")),
    path("intercambiar_producto/", include("intercambiar_producto.urls")),
    path("gestion_de_servicios/", include("gestion_de_servicios.urls")),
    path("gestion_de_datos/", include("gestion_de_datos.urls")),
    path("catalogo/", include("catalogo.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_de_servicios/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.utils.text import slugify 
from gestion_de_sucursales.models import Sucursal 
from django.utils import timezone
from datetime import timedelta

class ConfiguracionServicio(models.Model):
    costo_publicacion = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    duracion_publicacion_dias = models.IntegerField(default=30)

    def __str__(self):
        return f"Configuración de Servicio"

    @classmethod
    def get_solo_instance(cls):
        # Obtener o crear la única instancia de ConfiguracionServicio
        instance, created = cls.objects.get_or_create(pk=1)
        return instance


class Tarjeta(models.Model):
    id = models.AutoField(primary_key=True)
    nombre_apellido = models.CharField(max_length=100)
    numero = models.CharField(max_length=19)
    mes_vencimiento = models.IntegerField(null=True, blank=True)
    año_vencimiento = models.IntegerField(null=True, blank=True)
    cvv = models.CharField(max_length=3)
    saldo = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return str(self.id)
    

class PagoServicio(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=20, decimal_places=2) 
    fecha = models.DateField(null=True, blank=True)
    tarjeta = models.ForeignKey(Tarjeta, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return str(self.id) 
    
class Servicio(models.Model):
    ESTADOS = (
        ('cancelado', 'Cancelado'),
        ('pendiente', 'Pendiente'),   
        ('aceptado', 'Aceptado'),
        ('rechazado', 'Rechazado'),
        ('publicado', 'Publicado'),
        ('eliminado', 'Eliminado'),
        ('vencido', 'Vencido'),
    )
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, choices=ESTADOS, default='pendiente')
    ciudad = models.CharField(max_length=50, null=True, blank=True)
    imagen = models.ImageField(upload_to='imagenes/')
    descripcion = models.TextField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)    
    pago = models.ForeignKey(PagoServicio, on_delete=models.CASCADE, null=True, blank=True)
    fechaFin = models.DateField(null=True, blank=True)
    visible = models.BooleanField(default=True)
    #maximos_dias = models.IntegerField(null=True)  

    def save(self, *args, **kwargs):
        self.fechaFin = timezone.now().date() + timedelta(days=30) #ESTO BORRAR CUNADO USE LOS DIAS
        self.slug = slugify(str(self.id) + "-" + str(self.imagen))
        return super().save(*args , **kwargs)

    def __str__(self):
        return str(self.id) 
    
    @property
    def puede_eliminar(self):
        if self.fechaFin:
            return self.fechaFin <= timezone.now().date()
        return False
    

gestion_de_servicios/forms.py
from django import forms
from django.forms import ModelForm
from .models import Servicio
from .models import ConfiguracionServicio

class ConfiguracionServicioForm(forms.ModelForm):
    costo_publicacion = forms.DecimalField(min_value=1, label='Costo de Publicación')
    duracion_publicacion_dias = forms.IntegerField(min_value=1, label='Duración de Publicación (días)')

    class Meta:
        model = ConfiguracionServicio
        fields = ['costo_publicacion', 'duracion_publicacion_dias']

        
class ServicioForm(ModelForm):
    class Meta():
        model = Servicio
        fields = ("ciudad", "imagen", "descripcion")
        labels = {
            "ciudad" : "",
            "imagen": "",
            "descripcion": "",
        }
        
        widgets = {
            "ciudad": forms.TextInput(attrs={"class": "form-control", "placeholder": "Ciudad del servicio"}),
            "imagen": forms.FileInput(attrs={"class": "form-control", "placeholder": "Flyer del servicio"}),
            "descripcion": forms.Textarea(attrs={"class": "form-control", "placeholder": "Descripcion del servicio"}),
        }   

gestion_de_servicios/views.py
from django.shortcuts import render, redirect
from gestion_de_sucursales.models import Sucursal
from .models import PagoServicio, Servicio, Tarjeta
from datetime import datetime
from django.contrib import messages
from .forms import ServicioForm
from django.core.exceptions import ValidationError
from PIL import Image, ImageChops
from django.core.mail import send_mail
from iniciar_sesion.decoradores import *
from django.db.models import Q
from .models import ConfiguracionServicio
from .forms import ConfiguracionServicioForm
from django.shortcuts import get_object_or_404
#from django.utils import timezone
#from datetime import timedelta

# Create your views here.
@soy_cliente
def mis_servicios_view(request):
    return render(request, "gestion_de_servicios/mis_servicios.html")

@soy_cliente
def listar_solicitudes_view(request):    
    usuario = request.user
    queryset = Servicio.objects.filter(cliente=usuario)
    context = {
        "lista": queryset
    }
    
    return render(request, "gestion_de_servicios/listar_solicitudes.html", context)

@soy_cliente
def subir_servicio_view(request):
    sucursales = Sucursal.objects.all()
    if request.method == "POST":
        form = ServicioForm(request.POST, request.FILES)

        imagen = request.FILES.get('imagen')
        if imagen:
            formato_valido, mensaje_error = verificar_formato_imagen(imagen)
            if not formato_valido:
                messages.error(request, mensaje_error)
                return render(request, "gestion_de_servicios/solicitar_servicio.html", {
                    "form": form,
                    "sucursales": sucursales,
                })
        else:
            messages.error(request, "Es obligatorio subir la imagen del flyer del servicio.")
            return render(request, "gestion_de_servicios/solicitar_servicio.html", {
                    "form": form,
                    "sucursales": sucursales,
                })
        
        if form.is_valid():          
            servicio = form.save(commit=False)
            servicio.cliente = request.user
            # servicio.maximo_dias = configuracion_servicio.duracion_publicacion_dias 
            servicio.save()
            
            if are_images_equal(servicio.id):
                servicio.delete()
                messages.error(request, "¡Este servicio ya fue ofertado en el sitio!")
            else:
                messages.success(request, "¡Se ha solicitado la publicacion del servicio correctamente!")
            return redirect("mis_servicios")
        
    else:
        form = ServicioForm()
        
    return render(request, "gestion_de_servicios/solicitar_servicio.html", {
        "form": form,
        "sucursales": sucursales,
    })

def are_images_equal(servicio_slug):
    servicio = Servicio.objects.get(id=servicio_slug)
    comparativas = Servicio.objects.exclude(id=servicio_slug)

    image_one = Image.open(servicio.imagen.path).convert('RGB')

    for servicio_comp in comparativas:
        try:
            image_two = Image.open(servicio_comp.imagen.path).convert('RGB')
            diff = ImageChops.difference(image_one, image_two)
            if not diff.getbbox():
                return True

        except FileNotFoundError:
            continue

    return False

def verificar_formato_imagen(imagen):
    try:
        formato = imagen.name.split('.')[-1].lower()
        if formato not in ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tif', 'tiff', 'webp', 'ico', 'svg']:
            mensaje_error = "Formato de imagen inválido. Los formatos admitidos son: .jpg, .jpeg, .png, .gif, .bmp, .tif, .tiff, .webp, .ico, .svg"
            return False, mensaje_error
        return True, None
    except AttributeError:
        raise ValidationError("Se produjo un error al verificar el formato de la imagen.")   
    
@soy_cliente
def ver_imagen_view(request, slug):
    servicio = get_object_or_404(Servicio, slug=slug)
    
    if request.method == "POST":
        accion = request.POST.get('accion')
        if accion == 'cancelar':
            servicio.estado = 'cancelado'
            servicio.visible = False
            servicio.save()
            messages.success(request, "Publicación de servicio cancelada con éxito")
            return redirect("listar_solicitudes")
        elif accion == 'eliminar':
            servicio.estado = 'eliminado'
            servicio.visible = False
            servicio.save()
            messages.success(request, "Servicio eliminado con éxito")
            return redirect("listar_solicitudes")  
        
    context = {
        'servicio': servicio,
    }
    return render(request, "gestion_de_servicios/ver_imagen.html", context)

@soy_cliente
def pagar_publicacion_view(request, slug):
    servicio = Servicio.objects.get(slug=slug)
    aux = ConfiguracionServicio.objects.get(id=1)
    montoAux = aux.costo_publicacion
    if request.method == 'POST':
        numero_tarjeta = request.POST.get('numero_tarjeta')
        nombre_dueño = request.POST.get('nombre_dueño')
        fecha_vencimiento = request.POST.get('fecha_vencimiento')
        codigo_seguridad = request.POST.get('codigo_seguridad')
        
        if not all([numero_tarjeta, nombre_dueño, fecha_vencimiento, codigo_seguridad]):
            messages.error(request, "Todos los campos son obligatorios.")
            return redirect('pagar_publicacion', slug=slug)
        
        
        if numero_tarjeta[0] in ('4', '5'):        
            fecha_vencimiento = str(fecha_vencimiento)
            if isinstance(fecha_vencimiento, str):
                partes = fecha_vencimiento.split('/')
                if len(partes) == 2:
                    mes, año = partes
                    mes_vencimiento = int(mes)
                    año_vencimiento = int(año)
                else:
                    print(partes)
                    print(len(partes))
                    messages.error(request, "Len no es 2.")
                    return redirect('pagar_publicacion', slug=slug)
            else:
                messages.error(request, "No es string.")
                return redirect('pagar_publicacion', slug=slug)
            tarjeta = Tarjeta.objects.get(numero=numero_tarjeta)    
            if (tarjeta):
                if (tarjeta.nombre_apellido != nombre_dueño): 
                    messages.error(request, "El nombre ingresado no coincide con el nombre del dueño de la tarjeta.")
                    return redirect('pagar_publicacion', slug=slug)
                if (tarjeta.mes_vencimiento != mes_vencimiento or tarjeta.año_vencimiento != año_vencimiento):
                    messages.error(request, "La fecha ingresada no coincide con la fecha de vencimiento de la tarjeta.")
                    return redirect('pagar_publicacion', slug=slug)
                if (tarjeta.mes_vencimiento < 7 and tarjeta.año_vencimiento <= 2024):
                    messages.error(request, "La tarjeta caducó.")
                    return redirect('pagar_publicacion', slug=slug)                
                if (tarjeta.cvv != codigo_seguridad):
                    messages.error(request, "El codigo ingresado no coincide con el codigo de seguridad de la tarjeta.")
                    return redirect('pagar_publicacion', slug=slug)
                if (tarjeta.saldo < montoAux):
                    messages.error(request, "El saldo de la tarjeta es insuficiente.")
                    return redirect('pagar_publicacion', slug=slug)
            else :
                messages.error(request, "Esta tarjeta no se encuentra registrada en el sistema.")
                return redirect('pagar_publicacion', slug=slug)        
            
            tarjeta.saldo = tarjeta.saldo - montoAux
            tarjeta.save()
            
            pagoAux = PagoServicio(
                cliente=request.user,
                monto=montoAux,
                fecha=datetime.now().date(),  
                tarjeta=tarjeta
            )
            pagoAux.save()
            servicio.estado = 'publicado'
            servicio.pago = pagoAux
            #servicio.fechaFin = timezone.now().date() + timedelta(servicio.maximos_dias)
            servicio.save()
            

            messages.success(request, "Pago realizado con éxito.")
            return redirect('listar_solicitudes')  
        else:
            messages.error(request, "Solo se aceptan tarjetas Visa o MasterCard.")
            return redirect('pagar_publicacion', slug=slug)
    context = {
        'servicio': servicio,
        'monto': montoAux,
    }
    return render(request, "gestion_de_servicios/pagar_publicacion.html", context)

@super_user 
def listar_solicitudes_clientes_view(request):    
    queryset = Servicio.objects.filter(visible=True, estado__in=['pendiente', 'publicado'])
    context = {
        "lista": queryset
    }
    return render(request, "gestion_de_servicios/listar_solicitudes_clientes.html", context)

@super_user 
def eliminar_servicio_view(request, slug):
    servicio = Servicio.objects.get(slug=slug)
    if request.method == "POST":
        motivo = request.POST.get('motivo')
        if not motivo.strip():
            messages.error(request, "Completa la casilla de texto, el motivo no puede estar vacio")
        else:
            servicio.estado = 'eliminado'
            servicio.visible = False
            servicio.save()
            cliente = servicio.cliente
            subject = 'Eliminacion de Servicio'
            message = f'Hola {cliente.username},\n\nTu publicacion de servicio ha sido eliminada, este es el motivo:\n\n{motivo}\n\n'
            from_email = 'noreply@ferreplus.com'
            to_email = [cliente.email]
            send_mail(subject, message, from_email, to_email)
            messages.success(request, "El servicio ha sido eliminado.")
            return redirect("listar_solicitudes_clientes")
    context = {
        'servicio': servicio
    }

gestion_de_servicios/templates/gestion_de_servicios/config.html
{% extends "homepage/base.html" %}

<!DOCTYPE html>
<html lang="en">
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configuración del Servicio</title>
</head>

<body>
    <h1>Configuración del Servicio</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    {% endblock %}
</body>

</html>

gestion_de_servicios/templates/gestion_de_servicios/evaluar_servicio.html
{% extends "homepage/base.html" %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
      {% block content %}
      <style> 
        .carousel-item {
          justify-content: center; 
          align-items: center; 
          height: 50vh; 
        }
    
        .carousel-item img {
            max-width: 100%; 
            max-height: 100%; 
            object-fit: contain; 
        }
      </style>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{ servicio.imagen.url }}" class="d-block w-100" alt="...">
            </div>
        </div>
        <div class="card-body">
          <div class="mb-4">
            {% if servicio.descripcion %}
            <h6 class="display-8">Descripción: {{ servicio.descripcion }}</h6>
            {% endif %}
          </div>
          <div class="mb-4">
              <h8 class="display-8">Ciudad a publicar: {{ servicio.ciudad }} </h8>
          </div>
        </div>
        <div class="text-center">
            <form method="post">
              {% csrf_token %}
              <button type="submit" name="accion" value="aceptar" class="btn btn-success" onclick="return confirm('¿Estás seguro de que deseas Aceptar este servicio?')">Aceptar</button>
              <button type="submit" name="accion" value="rechazar" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas Rechazar este servicio?')">Rechazar</button>
            </form>
            <br><br>
        </div>
  {% endblock %}        

    </body>
</html>

gestion_de_servicios/templates/gestion_de_servicios/listar_solicitudes.html
{% extends "homepage/base.html" %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% block content %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% if lista %}
                {% for servicio in lista %}
                    <div class="col">
                        <div class="card">
                            <img src="{{ servicio.imagen.url }}" class="card-img-top img-thumbnail" style="height: 300px;">
                            <div class="card-body">
                                <h5 class="card-title"></h5>
                                <a href="{% url 'ver_imagen' servicio.slug %}" class="btn btn-primary stretched-link">Ver estado</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h1 class="display-1">No hay solicitudes de servicios</h1>
            {% endif %}
        </div>
    {% endblock %}
    </body>
</html>

gestion_de_servicios/templates/gestion_de_servicios/listar_solicitudes_clientes.html
{% extends "homepage/base.html" %}

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    {% block content %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% if lista %}
        {% for servicio in lista %}
        <div class="col">
            <div class="card">
                <img src="{{ servicio.imagen.url }}" class="card-img-top img-thumbnail" style="height: 300px;">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    {% if servicio.estado == 'pendiente' %}
                    <a href="{% url 'evaluar_servicio' servicio.slug %}"
                        class="btn btn-primary stretched-link">Evaluar</a>
                    {% endif %}
                    {% if servicio.estado == 'publicado' and servicio.puede_eliminar %}
                    <a href="{% url 'eliminar_servicio' servicio.slug %}" class="btn btn-danger btn-sm mt-2"
                        onclick="return confirm('¿Estás seguro de que deseas eliminar el servicio?');">Eliminar</a>
                    {% endif %}
                    <p><strong>Fecha de Fin:</strong> {{ servicio.fechaFin }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h1 class="display-1">No hay solicitudes pendientes</h1>
        {% endif %}
    </div>
    
    {% endblock %}
</body>

</html>

gestion_de_servicios/templates/gestion_de_servicios/mandar_motivo.html
{% extends "homepage/base.html" %}

<html>
    <body>
        {% block content %}
        <h4 class="display-4">Escribe el motivo de tu decision</h4>
        <form method="post">
            {% csrf_token %}
            <div class="form-floating">
                <textarea class="form-control" placeholder="Motivo del rechazo" id="floatingTextarea2" style="height: 100px" name="motivo"></textarea>
                <label for="floatingTextarea2">Motivo del rechazo</label>
            </div>
            <br></br>
            <div>
                <button type="submit" class="btn btn-success" onclick="return confirm('¿Estás seguro de que deseas enviar este motivo?')">Enviar motivo</button>
            </div>
        </form>
        {% endblock %}
    </body>
</html>

gestion_de_servicios/templates/gestion_de_servicios/mis_servicios.html
{% extends "homepage/base.html" %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title></title>
    {% block content %}
</head>

<body>
    <div>
        <section class="vh-100 gradient-custom d-flex justify-content-center align-items-center">
            <div class="card text-center bg-dark" style="width: 300px;">
                <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
                    <a type="button" class="btn btn-primary" href="{% url 'listar_solicitudes' %}">Ver solicitudes</a>
                    <a type="button" class="btn btn-primary" href="{% url 'subir_servicio' %}">Solicitar servicio</a>
                </div>
            </div>
        </section>
    </div>
</body>
{% endblock %}

</html>

gestion_de_servicios/templates/gestion_de_servicios/servicios_publicados.html
{% extends "homepage/base.html" %}

{% block content %}
<div class="container">
    <h2>Servicios Publicados</h2>
    <form class="mb-3" method="GET" action="{% url 'servicios_publicados' %}">
        <div class="row">
            <div class="col-md-6">
                <label for="nombre">Buscar por nombre:</label>
                <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Nombre del servicio"
                    value="{{ request.GET.nombre|default_if_none:'' }}">
            </div>
            <div class="col-md-6">
                <label for="ciudad">Seleccionar ciudad:</label>
                <select id="ciudad" name="ciudad" class="form-control">
                    <option value="">Todas las ciudades</option>
                    {% for city in ciudades %}
                    <option value="{{ city }}">{{ city }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </form>

    {% for servicio in servicios %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ servicio.cliente }}</h5>
            <p class="card-text">{{ servicio.descripcion }}</p>
            <img src="{{ servicio.imagen.url }}" alt="{{ servicio.descripcion }}" class="img-fluid">
            <!-- Otros detalles del servicio -->
        </div>
    </div>
    <hr> <!-- Línea horizontal como separador -->
    {% endfor %}
</div>
{% endblock %}

gestion_de_servicios/templates/gestion_de_servicios/solicitar_servicio.html
{% extends "homepage/base.html" %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
    {% block content %}    

        <h3>Solicitar la publicacion de un servicio</h3>

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                    
                <div class="mb-3">
                    <label for="ciudad" class="form-label">Ciudad:</label>
                    <select class="form-select" id="ciudad" name="ciudad" required>
                        <option value="" selected disabled>Seleccionar Ciudad</option>
                        {% for sucursal in sucursales %}
                        <option value="{{ sucursal.ciudad }}">{{ sucursal.ciudad }}</option>
                        {% endfor %}
                    </select>
                </div>      
                <label><strong> Formatos de imágenes admitidos: .jpg, .jpeg, .png, .gif, .bmp, .tif, .tiff, .webp, .ico, .svg </strong></label>              
                <div class="custom-file">
                    <input type="file" id="id_imagen" name="imagen" class="custom-file-input">
                    <label class="custom-file-label" for="id_imagen"> Selecciona el flyer para tu servicio. <strong> Recorda agregar algun medio para contactarte. </strong></label>
                </div>
                <div>
                    <label> Descripcion de tu servicio (opcional). <strong> También podés agregar acá un medio para contactarte. </strong> </label>
                    {{ form.descripcion.label_tag }}
                    {{ form.descripcion }}
                    
                </div>
                <br></br> 
                <input type="submit" value="Solicitar" class="btn btn-dark">
            </form>  
             
    {% endblock %}
    </body>
</html>

gestion_de_servicios/templates/gestion_de_servicios/ver_historial.html
{% extends "homepage/base.html" %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        {% block content %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% if lista %}
                {% for servicio in lista %}
                    <div class="col">
                        <div class="card">
                            <img src="{{ servicio.imagen.url }}" class="card-img-top img-thumbnail" style="height: 300px;">
                            <p><strong>Descripción:</strong> {{ servicio.descripcion }}</p>
                            <p><strong>Fecha de Fin:</strong> {{ servicio.fechaFin }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h1 class="display-1">No hay solicitudes de servicios eliminadas</h1>
            {% endif %}
        </div>
    {% endblock %}
    </body>
</html>

gestion_de_servicios/templates/gestion_de_servicios/ver_imagen.html
{% extends "homepage/base.html" %}

<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  {% block content %}
  <style>
    .carousel-item {
      justify-content: center;
      align-items: center;
      height: 50vh;
    }

    .carousel-item img {
      max-width: 100%;
      max-height: 100%;
      object-fit: contain;
    }
  </style>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ servicio.imagen.url }}" class="d-block w-100" alt="...">
    </div>
  </div>
  <div class="card-body">

    <div class="mb-4">
      {% if servicio.descripcion %}
      <h6 class="display-8">Descripcion: {{ servicio.descripcion }}</h6>
      {% endif %}
    </div>
    <div class="mb-4">
      <h8 class="display-8">Ciudad a publicar: {{ servicio.ciudad }}</h8>
    </div>
    <div class="mb-4">
      <h8 class="display-8">Estado: {% if servicio.estado == 'pendiente' %} Pendiente de aprobacion
        {% elif servicio.estado == 'aceptado' %} Aceptado, ya podes pagarlo para publicarlo
        {% elif servicio.estado == 'rechazado' %} Rechazado, revisa tu correo para saber el motivo
        {% elif servicio.estado == 'publicado' %} Tu servicio ya esta siendo ofertado en nuestro sitio!
        {% elif servicio.estado == 'eliminado' %} Tu servicio fue eliminado de nuestro sitio! Revisa tu correo para saber el motivo {% endif %}</h8>
    </div>

    {% if servicio.estado == 'aceptado' %}
    <a href="{% url 'pagar_publicacion' servicio.slug %}" class="btn btn-primary">Pagar</a>
    {% endif %}
    {% if servicio.estado == 'pendiente' %}
    <form method="post">
      {% csrf_token %}
      <button type="submit" name="accion" value="cancelar" class="btn btn-danger"
        onclick="return confirm('¿Estás seguro de que deseas Cancelar esta publicacion de Servicio?')">Cancelar</button>
    </form>
    {% endif %}
    {% if servicio.estado == 'publicado' %}
    <form method="post">
      {% csrf_token %}
      <button type="submit" name="accion" value="eliminar" class="btn btn-danger"
        onclick="return confirm('¿Estás seguro de que deseas eliminar este servicio? Esta acción no se puede deshacer')">Eliminar</button>
    </form>
    {% endif %}
  </div>

  {% endblock %}

</body>

</html>